# Generated by Django 6.0.1 on 2026-02-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create Feature'), ('UPDATE', 'Update Feature'), ('DELETE', 'Delete Feature')], max_length=10)),
                ('feature_name', models.CharField(max_length=255)),
                ('new_value', models.BooleanField(blank=True, null=True)),
                ('performed_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
